[tool.poetry]
name = "aurelio-sdk"
version = "0.0.1"
description = "Aurelio API SDK"
authors = ["Aurelio Team <hello@aurelio.ai>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
